// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/';
};

export type GetHealthResponses = {
    200: unknown;
};

export type GetHealthReadyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/ready';
};

export type GetHealthReadyResponses = {
    200: unknown;
};

export type PostAuthDeviceInitData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/device/init';
};

export type PostAuthDeviceInitResponses = {
    200: {
        deviceCode: string;
        userCode: string;
        expiresAt: unknown | string | number;
        verificationUri: string;
        interval: number;
    };
};

export type PostAuthDeviceInitResponse = PostAuthDeviceInitResponses[keyof PostAuthDeviceInitResponses];

export type PostAuthDeviceConfirmData = {
    body: {
        userCode: string;
    };
    path?: never;
    query?: never;
    url: '/auth/device/confirm';
};

export type PostAuthDeviceConfirmResponses = {
    200: {
        success: boolean;
    };
};

export type PostAuthDeviceConfirmResponse = PostAuthDeviceConfirmResponses[keyof PostAuthDeviceConfirmResponses];

export type PostAuthDevicePollData = {
    body: {
        deviceCode: string;
    };
    path?: never;
    query?: never;
    url: '/auth/device/poll';
};

export type PostAuthDevicePollResponses = {
    200: {
        status: string;
        message: string;
    } | {
        status: string;
        accessToken: string;
        user: {
            id: string;
            email: string;
            name: string | unknown;
        };
    } | {
        status: string;
        error: string;
    };
};

export type PostAuthDevicePollResponse = PostAuthDevicePollResponses[keyof PostAuthDevicePollResponses];

export type PostAuthSignInEmailData = {
    body: {
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/sign-in/email';
};

export type PostAuthSignInEmailResponses = {
    200: unknown;
};

export type PostAuthSignUpEmailData = {
    body: {
        email: string;
        password: string;
        name?: string;
    };
    path?: never;
    query?: never;
    url: '/auth/sign-up/email';
};

export type PostAuthSignUpEmailResponses = {
    200: unknown;
};

export type GetAuthSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/session';
};

export type GetAuthSessionResponses = {
    200: unknown;
};

export type PostAuthSignOutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/sign-out';
};

export type PostAuthSignOutResponses = {
    200: unknown;
};

export type GetDownloadHooksSdkVersionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/download/hooks-sdk/version';
};

export type GetDownloadHooksSdkVersionResponses = {
    200: unknown;
};

export type GetApiV1WorkspacesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/workspaces/';
};

export type GetApiV1WorkspacesResponses = {
    200: unknown;
};

export type PostApiV1WorkspacesData = {
    body: {
        name: string;
        slug: string;
        ownerId: string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/workspaces/';
};

export type PostApiV1WorkspacesResponses = {
    200: unknown;
};

export type DeleteApiV1WorkspacesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/workspaces/{id}';
};

export type DeleteApiV1WorkspacesByIdResponses = {
    200: unknown;
};

export type GetApiV1WorkspacesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/workspaces/{id}';
};

export type GetApiV1WorkspacesByIdResponses = {
    200: unknown;
};

export type PutApiV1WorkspacesByIdData = {
    body: {
        name?: string;
        slug?: string;
        ownerId?: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/workspaces/{id}';
};

export type PutApiV1WorkspacesByIdResponses = {
    200: unknown;
};

export type GetApiV1WorkspacesStreamData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/workspaces/stream';
};

export type GetApiV1WorkspacesStreamResponses = {
    200: unknown;
};

export type GetApiV1HookEventsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: string;
        offset?: string;
    };
    url: '/api/v1/hook-events/';
};

export type GetApiV1HookEventsResponses = {
    200: unknown;
};

export type PostApiV1HookEventsData = {
    body: {
        projectId: string;
        sessionId: string;
        eventName: string;
        toolName?: string;
        payload: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/v1/hook-events/';
};

export type PostApiV1HookEventsResponses = {
    200: unknown;
};

export type GetApiV1HookEventsRecentData = {
    body?: never;
    path?: never;
    query?: {
        seconds?: string;
        projectId?: string;
    };
    url: '/api/v1/hook-events/recent';
};

export type GetApiV1HookEventsRecentResponses = {
    200: unknown;
};

export type GetApiV1HookEventsStreamData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Project ID to filter hook events
         */
        projectId: string;
        /**
         * Optional session ID to filter hook events
         */
        sessionId?: string;
    };
    url: '/api/v1/hook-events/stream';
};

export type GetApiV1HookEventsStreamResponses = {
    200: unknown;
};

export type GetApiV1SessionsRecentData = {
    body?: never;
    path?: never;
    query?: {
        seconds?: number;
        projectId?: string;
    };
    url: '/api/v1/sessions/recent';
};

export type GetApiV1SessionsRecentResponses = {
    200: unknown;
};

export type GetApiV1SessionsStreamData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Project ID to filter sessions
         */
        projectId: string;
    };
    url: '/api/v1/sessions/stream';
};

export type GetApiV1SessionsStreamResponses = {
    200: unknown;
};

export type GetApiV1SummariesRecentData = {
    body?: never;
    path?: never;
    query?: {
        seconds?: number;
        projectId?: string;
        sessionId?: string;
    };
    url: '/api/v1/summaries/recent';
};

export type GetApiV1SummariesRecentResponses = {
    200: unknown;
};

export type GetApiV1SummariesStreamData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Project ID to filter summaries
         */
        projectId: string;
        /**
         * Optional session ID to filter summaries
         */
        sessionId?: string;
    };
    url: '/api/v1/summaries/stream';
};

export type GetApiV1SummariesStreamResponses = {
    200: unknown;
};

export type GetApiV1ChatRecentData = {
    body?: never;
    path?: never;
    query?: {
        seconds?: number;
        projectId?: string;
        sessionId?: string;
    };
    url: '/api/v1/chat/recent';
};

export type GetApiV1ChatRecentResponses = {
    200: unknown;
};

export type GetApiV1ChatStreamData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Project ID to filter chat messages
         */
        projectId: string;
        /**
         * Optional session ID to filter chat messages
         */
        sessionId?: string;
    };
    url: '/api/v1/chat/stream';
};

export type GetApiV1ChatStreamResponses = {
    200: unknown;
};

export type GetApiV1CredentialsData = {
    body?: never;
    path?: never;
    query?: {
        workspaceId?: string;
        userId?: string;
        provider?: string;
    };
    url: '/api/v1/credentials/';
};

export type GetApiV1CredentialsResponses = {
    200: unknown;
};

export type PostApiV1CredentialsData = {
    body: {
        name: string;
        provider: string;
        apiKey: string;
        workspaceId?: string | unknown;
        userId?: string | unknown;
        isActive?: boolean;
    };
    path?: never;
    query?: never;
    url: '/api/v1/credentials/';
};

export type PostApiV1CredentialsResponses = {
    200: unknown;
};

export type DeleteApiV1CredentialsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/credentials/{id}';
};

export type DeleteApiV1CredentialsByIdResponses = {
    200: unknown;
};

export type GetApiV1CredentialsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/credentials/{id}';
};

export type GetApiV1CredentialsByIdResponses = {
    200: unknown;
};

export type PutApiV1CredentialsByIdData = {
    body: {
        name?: string;
        apiKey?: string;
        isActive?: boolean;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/credentials/{id}';
};

export type PutApiV1CredentialsByIdResponses = {
    200: unknown;
};

export type GetApiV1LlmConfigsData = {
    body?: never;
    path?: never;
    query?: {
        projectId?: string;
        provider?: string;
        isActive?: boolean;
    };
    url: '/api/v1/llm-configs/';
};

export type GetApiV1LlmConfigsResponses = {
    200: unknown;
};

export type PostApiV1LlmConfigsData = {
    body: {
        name: string;
        provider: string;
        model: string;
        systemPrompt: string;
        temperature?: number;
        maxTokens?: number;
        apiUrl?: string | unknown;
        credentialId: string;
        projectId?: string | unknown;
        isActive?: boolean;
    };
    path?: never;
    query?: never;
    url: '/api/v1/llm-configs/';
};

export type PostApiV1LlmConfigsResponses = {
    200: unknown;
};

export type DeleteApiV1LlmConfigsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/llm-configs/{id}';
};

export type DeleteApiV1LlmConfigsByIdResponses = {
    200: unknown;
};

export type GetApiV1LlmConfigsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/llm-configs/{id}';
};

export type GetApiV1LlmConfigsByIdResponses = {
    200: unknown;
};

export type PutApiV1LlmConfigsByIdData = {
    body: {
        name?: string;
        model?: string;
        systemPrompt?: string;
        temperature?: number;
        maxTokens?: number;
        apiUrl?: string | unknown;
        credentialId?: string;
        isActive?: boolean;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/llm-configs/{id}';
};

export type PutApiV1LlmConfigsByIdResponses = {
    200: unknown;
};

export type GetApiV1LlmConfigsDefaultsPromptsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/llm-configs/defaults/prompts';
};

export type GetApiV1LlmConfigsDefaultsPromptsResponses = {
    200: unknown;
};

export type GetApiV1TodosRecentData = {
    body?: never;
    path?: never;
    query?: {
        seconds?: number;
        projectId?: string;
    };
    url: '/api/v1/todos/recent';
};

export type GetApiV1TodosRecentResponses = {
    200: unknown;
};

export type GetApiV1TodosStreamData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Project ID to filter todos
         */
        projectId: string;
    };
    url: '/api/v1/todos/stream';
};

export type GetApiV1TodosStreamResponses = {
    200: unknown;
};

export type GetApiV1TodosSessionBySessionIdData = {
    body?: never;
    path: {
        sessionId: string;
    };
    query?: never;
    url: '/api/v1/todos/session/{sessionId}';
};

export type GetApiV1TodosSessionBySessionIdResponses = {
    200: unknown;
};

export type GetApiV1FailuresRecentData = {
    body?: never;
    path?: never;
    query?: {
        seconds?: number;
    };
    url: '/api/v1/failures/recent';
};

export type GetApiV1FailuresRecentResponses = {
    200: unknown;
};

export type GetApiV1PersonasData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Project ID to filter personas
         */
        projectId: string;
    };
    url: '/api/v1/personas/';
};

export type GetApiV1PersonasResponses = {
    200: unknown;
};

export type PostApiV1PersonasData = {
    body: {
        /**
         * Project ID
         */
        projectId: string;
        /**
         * Persona name
         */
        name: string;
        /**
         * URL-safe slug
         */
        slug: string;
        /**
         * Persona role (flexible text)
         */
        role: string;
        /**
         * Hex color (e.g., #3B82F6)
         */
        color: string;
        /**
         * Voice identifier for TTS
         */
        voice?: string;
        /**
         * Persona description
         */
        description?: string;
        /**
         * Set as default persona
         */
        isDefault?: boolean;
        /**
         * Active status
         */
        isActive?: boolean;
    };
    path?: never;
    query?: never;
    url: '/api/v1/personas/';
};

export type PostApiV1PersonasResponses = {
    200: unknown;
};

export type DeleteApiV1PersonasByIdData = {
    body?: never;
    path: {
        /**
         * Persona UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/personas/{id}';
};

export type DeleteApiV1PersonasByIdResponses = {
    200: unknown;
};

export type GetApiV1PersonasByIdData = {
    body?: never;
    path: {
        /**
         * Persona UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/personas/{id}';
};

export type GetApiV1PersonasByIdResponses = {
    200: unknown;
};

export type PutApiV1PersonasByIdData = {
    body: {
        name?: string;
        slug?: string;
        role?: string;
        color?: string;
        voice?: string;
        description?: string;
        isDefault?: boolean;
        isActive?: boolean;
    };
    path: {
        /**
         * Persona UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/personas/{id}';
};

export type PutApiV1PersonasByIdResponses = {
    200: unknown;
};

export type GetApiV1PersonasBySlugByProjectIdBySlugData = {
    body?: never;
    path: {
        /**
         * Project ID
         */
        projectId: string;
        /**
         * Persona slug
         */
        slug: string;
    };
    query?: never;
    url: '/api/v1/personas/by-slug/{projectId}/{slug}';
};

export type GetApiV1PersonasBySlugByProjectIdBySlugResponses = {
    200: unknown;
};

export type GetApiV1PersonasDefaultByProjectIdData = {
    body?: never;
    path: {
        /**
         * Project ID
         */
        projectId: string;
    };
    query?: never;
    url: '/api/v1/personas/default/{projectId}';
};

export type GetApiV1PersonasDefaultByProjectIdResponses = {
    200: unknown;
};

export type PostApiV1PersonasByIdSetDefaultData = {
    body?: never;
    path: {
        /**
         * Persona UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/personas/{id}/set-default';
};

export type PostApiV1PersonasByIdSetDefaultResponses = {
    200: unknown;
};

export type GetApiV1PersonasByIdSkillsData = {
    body?: never;
    path: {
        /**
         * Persona UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/personas/{id}/skills';
};

export type GetApiV1PersonasByIdSkillsResponses = {
    200: unknown;
};

export type PostApiV1PersonasByIdSkillsData = {
    body: {
        /**
         * Skill file name (e.g., ui-qa-tester)
         */
        skillName: string;
        /**
         * Load order priority (lower = higher priority)
         */
        priority?: number;
    };
    path: {
        /**
         * Persona UUID
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/personas/{id}/skills';
};

export type PostApiV1PersonasByIdSkillsResponses = {
    200: unknown;
};

export type DeleteApiV1PersonasByIdSkillsBySkillNameData = {
    body?: never;
    path: {
        /**
         * Persona UUID
         */
        id: string;
        /**
         * Skill name to detach
         */
        skillName: string;
    };
    query?: never;
    url: '/api/v1/personas/{id}/skills/{skillName}';
};

export type DeleteApiV1PersonasByIdSkillsBySkillNameResponses = {
    200: unknown;
};

export type GetApiV1PersonasStreamData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by project ID
         */
        projectId?: string;
    };
    url: '/api/v1/personas/stream';
};

export type GetApiV1PersonasStreamResponses = {
    200: unknown;
};
