/**
 * Database Schema Exports
 * All tables, relations, and types
 */

// Export auth tables
export { users, type User, type NewUser } from './users';
export { sessions, type Session, type NewSession } from './sessions';
export { accounts, type Account, type NewAccount } from './accounts';
export { deviceCodes, type DeviceCode, type NewDeviceCode } from './device-codes';

// Export workspace tables
export {
  workspaces,
  workspacesRelations,
  type Workspace,
  type NewWorkspace,
  type WorkspaceSettings,
  type WorkspaceSmsRateLimitSettings,
  type WorkspaceTwilioSettings,
  type WorkspaceEmailRateLimitSettings,
  type WorkspaceEmailComplianceSettings,
  type WorkspacePhoneNumber,
  type PhoneCountryCode,
  type PhoneCapability,
} from './workspaces';
export {
  workspaceMembers,
  workspaceMembersRelations,
  workspaceRoleEnum,
  workspaceMemberStatusEnum,
  type WorkspaceMember,
  type NewWorkspaceMember,
  type WorkspaceRole,
  type WorkspaceMemberStatus,
} from './workspace-members';
export {
  workspaceInvitations,
  workspaceInvitationsRelations,
  type WorkspaceInvitation,
  type NewWorkspaceInvitation,
} from './workspace-invitations';
export {
  workspaceAuditLog,
  workspaceAuditLogRelations,
  type WorkspaceAuditLog,
  type NewWorkspaceAuditLog,
} from './workspace-audit-log';

// Export project tables
export {
  projects,
  type Project,
  type NewProject,
} from './projects';

// Export Claude Code session tables
export {
  claudeSessions,
  type ClaudeSession,
  type NewClaudeSession,
  type TodoItem,
} from './claude-sessions';

// Export hook event tables
export {
  hookEvents,
  type HookEvent,
  type NewHookEvent,
} from './hook-events';

// Export event summary tables
export {
  eventSummaries,
  type EventSummary,
  type NewEventSummary,
  type HookEventName,
} from './event-summaries';

// Export chat message tables
export {
  chatMessages,
  type ChatMessage,
  type NewChatMessage,
  type ChatRole,
  type ChatMessageType,
} from './chat-messages';

// Export conversation tables
export {
  conversations,
  conversationsRelations,
  messages,
  messagesRelations,
  type Conversation,
  type NewConversation,
  type Message,
  type NewMessage,
  type MessageRole,
} from './conversations';

// Export LLM config tables
export {
  llmConfigs,
  llmConfigsRelations,
  type LLMConfig,
  type NewLLMConfig,
  type LLMProvider,
} from './llm-configs';

// Export LLM credential tables
export {
  llmCredentials,
  type LLMCredential,
  type NewLLMCredential,
} from './llm-credentials';

// Export LLM model catalog tables
export {
  llmModelCatalog,
  type LLMModelCatalogEntry,
  type NewLLMModelCatalogEntry,
} from './llm-model-catalog';

// Export voice tables
export {
  voices,
  type Voice,
  type NewVoice,
  type VoiceProvider,
  type VoiceGender,
} from './voices';

export {
  globalVoiceSettings,
  globalVoiceSettingsRelations,
  projectVoiceSettings,
  projectVoiceSettingsRelations,
  type GlobalVoiceSettings,
  type NewGlobalVoiceSettings,
  type ProjectVoiceSettings,
  type NewProjectVoiceSettings,
} from './voice-settings';

// Export model tables
export {
  models,
  type Model,
  type NewModel,
} from './models';

// Export pronunciation dictionary tables
export {
  pronunciationDictionaries,
  type PronunciationDictionary,
  type NewPronunciationDictionary,
} from './pronunciation-dictionaries';

// Export audio cache tables
export {
  audioCache,
  type AudioCache,
  type NewAudioCache,
} from './audio-cache';

// Export todos tables
export {
  todos,
  todosRelations,
  todoStatusEnum,
  type Todo,
  type NewTodo,
  type TodoWithMetadata,
} from './todos';

// Export AI Assistant tables
export {
  aiConversations,
  aiConversationsRelations,
  aiMessages,
  aiMessagesRelations,
  aiConfig,
  aiConfigRelations,
  aiToolInvocations,
  aiToolInvocationsRelations,
  aiRateLimits,
  aiRateLimitsRelations,
  aiClaudeCodeSessions,
  aiClaudeCodeSessionsRelations,
  type AiConversation,
  type NewAiConversation,
  type AiMessage,
  type NewAiMessage,
  type AiConfig,
  type NewAiConfig,
  type AiToolInvocation,
  type NewAiToolInvocation,
  type AiRateLimit,
  type NewAiRateLimit,
  type AiClaudeCodeSession,
  type NewAiClaudeCodeSession,
} from './ai-assistant';

// Export AI Intelligence tables
export {
  workspaceMemory,
  workspaceMemoryRelations,
  conversationSummaries,
  conversationSummariesRelations,
  workspaceSuggestions,
  workspaceSuggestionsRelations,
  tags,
  memoryTypeEnum,
  memoryStatusEnum,
  suggestionTypeEnum,
  suggestionSeverityEnum,
  suggestionStatusEnum,
  type WorkspaceMemory,
  type NewWorkspaceMemory,
  type MemoryType,
  type MemoryStatus,
  type ConversationSummary,
  type NewConversationSummary,
  type WorkspaceSuggestion,
  type NewWorkspaceSuggestion,
  type SuggestionType,
  type SuggestionSeverity,
  type SuggestionStatus,
  type Tag,
  type NewTag,
} from './ai-intelligence.schema';

// Export CRM tables
export {
  crmAccounts,
  crmAccountsRelations,
  crmContacts,
  crmContactsRelations,
  crmLeads,
  crmLeadsRelations,
  crmLeadScoreHistory,
  crmLeadScoreHistoryRelations,
  crmOpportunities,
  crmOpportunitiesRelations,
  crmActivities,
  crmActivitiesRelations,
  crmTimelineEvents,
  crmTimelineEventsRelations,
  crmLeadImports,
  crmCalls,
  crmCallsRelations,
  crmEmailTemplates,
  crmEmailTemplatesRelations,
  crmSmsTemplates,
  crmSmsTemplatesRelations,
  contactStatusEnum,
  lifecycleStageEnum,
  leadStatusEnum,
  opportunityStageEnum,
  opportunityStatusEnum,
  activityTypeEnum,
  activityStatusEnum,
  activityPriorityEnum,
  timelineEntityTypeEnum,
  timelineEventCategoryEnum,
  timelineActorTypeEnum,
  crmImportStatusEnum,
  type CrmAccount,
  type NewCrmAccount,
  type CrmContact,
  type NewCrmContact,
  type CrmLead,
  type NewCrmLead,
  type CrmLeadScoreHistory,
  type NewCrmLeadScoreHistory,
  type CrmOpportunity,
  type NewCrmOpportunity,
  type CrmActivity,
  type NewCrmActivity,
  type CrmTimelineEvent,
  type NewCrmTimelineEvent,
  type CrmLeadImport,
  type NewCrmLeadImport,
  type CrmCall,
  type NewCrmCall,
  type CrmSmsTemplate,
  type NewCrmSmsTemplate,
  type ContactStatus,
  type LifecycleStage,
  type LeadStatus,
  type OpportunityStage,
  type OpportunityStatus,
  type ActivityType,
  type ActivityStatus,
  type ActivityPriority,
  type TimelineEntityType,
  type TimelineEventCategory,
  type TimelineActorType,
  type CrmImportStatus,
} from './crm';

// Export Campaign tables
export {
  crmCampaigns,
  crmCampaignsRelations,
  crmCampaignRecipients,
  crmCampaignRecipientsRelations,
  crmCampaignMessages,
  crmCampaignMessagesRelations,
  crmAbTestResults,
  crmAbTestResultsRelations,
  crmDripEnrollments,
  crmDripEnrollmentsRelations,
  crmCampaignSnapshots,
  crmCampaignSnapshotsRelations,
  crmTestSmsSessions,
  crmTestSmsSessionsRelations,
  crmMockMessages,
  crmMockMessagesRelations,
  type CrmCampaign,
  type NewCrmCampaign,
  type CrmCampaignRecipient,
  type NewCrmCampaignRecipient,
  type CrmCampaignMessage,
  type NewCrmCampaignMessage,
  type CrmAbTestResult,
  type NewCrmAbTestResult,
  type CrmDripEnrollment,
  type NewCrmDripEnrollment,
  type CrmCampaignSnapshot,
  type NewCrmCampaignSnapshot,
  type CrmTestSmsSession,
  type NewCrmTestSmsSession,
  type CrmMockMessage,
  type NewCrmMockMessage,
  type CampaignObjective,
  type CampaignType,
  type CampaignStatus,
  type RecipientStatus,
  type CampaignChannel,
  type ABTestWinningCriteria,
  type DripEnrollmentStatus,
  type DripDelayUnit,
  type DripTriggerType,
  type DripTriggerAction,
  type RecipientSelectionConfig,
  type CampaignSnapshotData,
  type CampaignSnapshotMetadata,
} from './campaigns';

// Export SMS Rate Limits tables (Phase H.3)
export {
  crmSmsRateLimits,
  crmSmsRateLimitsRelations,
  type CrmSmsRateLimit,
  type NewCrmSmsRateLimit,
} from './sms-rate-limits';

// Export Email Suppressions & Rate Limits tables (Phase P)
export {
  crmEmailSuppressions,
  crmEmailSuppressionsRelations,
  crmEmailRateLimits,
  crmEmailRateLimitsRelations,
  type CrmEmailSuppression,
  type NewCrmEmailSuppression,
  type CrmEmailRateLimit,
  type NewCrmEmailRateLimit,
  type SuppressionReason,
  type SuppressionSourceType,
} from './email-suppressions';

// Export Campaign Automation tables
export {
  campaignSchedules,
  campaignSchedulesRelations,
  campaignRecurrences,
  campaignRecurrencesRelations,
  campaignTriggers,
  campaignTriggersRelations,
  campaignTriggerExecutions,
  campaignTriggerExecutionsRelations,
  campaignTemplates,
  campaignTemplatesRelations,
  campaignWorkflows,
  campaignWorkflowsRelations,
  campaignWorkflowEnrollments,
  campaignWorkflowEnrollmentsRelations,
  campaignWorkflowExecutions,
  campaignWorkflowExecutionsRelations,
  scheduleTypeEnum,
  scheduleStatusEnum,
  recurrencePatternEnum,
  recurrenceEndConditionEnum,
  triggerEventEnum,
  triggerStatusEnum,
  templateCategoryEnum,
  templateStatusEnum,
  workflowStatusEnum,
  workflowStepTypeEnum,
  workflowStepStatusEnum,
  workflowEnrollmentStatusEnum,
  type CampaignSchedule,
  type NewCampaignSchedule,
  type CampaignRecurrence,
  type NewCampaignRecurrence,
  type CampaignTrigger,
  type NewCampaignTrigger,
  type CampaignTriggerExecution,
  type NewCampaignTriggerExecution,
  type CampaignTemplate,
  type NewCampaignTemplate,
  type CampaignWorkflow,
  type NewCampaignWorkflow,
  type CampaignWorkflowEnrollment,
  type NewCampaignWorkflowEnrollment,
  type CampaignWorkflowExecution,
  type NewCampaignWorkflowExecution,
  type ScheduleType,
  type ScheduleStatus,
  type RecurrencePattern,
  type RecurrenceEndCondition,
  type TriggerEvent,
  type TriggerStatus,
  type TemplateCategory,
  type TemplateStatus,
  type WorkflowStatus,
  type WorkflowStepType,
  type WorkflowStepStatus,
  type WorkflowEnrollmentStatus,
} from './campaign-automation';

// Export Research tables
export {
  crmResearchSessions,
  crmResearchSessionsRelations,
  crmResearchQueries,
  crmResearchQueriesRelations,
  crmResearchFindings,
  crmResearchFindingsRelations,
  type CrmResearchSession,
  type NewCrmResearchSession,
  type CrmResearchQuery,
  type NewCrmResearchQuery,
  type CrmResearchFinding,
  type NewCrmResearchFinding,
} from './research';

// Export Contact Lists tables
export {
  crmContactLists,
  crmContactListsRelations,
  crmContactListMemberships,
  crmContactListMembershipsRelations,
  contactListTypeEnum,
  contactListStatusEnum,
  membershipSourceEnum,
  type CrmContactList,
  type NewCrmContactList,
  type CrmContactListMembership,
  type NewCrmContactListMembership,
  type ContactListType,
  type ContactListStatus,
  type MembershipSource,
} from './contact-lists';

// Export Enrichment tables
export {
  crmEnrichmentJobs,
  crmEnrichmentJobsRelations,
  crmEnrichmentResults,
  crmEnrichmentResultsRelations,
  crmToolCalls,
  crmToolCallsRelations,
  crmEnrichmentAbTests,
  crmEnrichmentPipelines,
  crmEnrichmentPipelinesRelations,
  crmPipelineStages,
  crmPipelineStagesRelations,
  crmTemplates,
  crmTemplatesRelations,
  crmScoringModels, // Legacy alias for crmTemplates
  crmScoringModelsRelations, // Legacy alias
  leadEnrichments,
  leadEnrichmentsRelations,
  leadEnrichmentConfigs,
  leadEnrichmentConfigsRelations,
  enrichmentJobTypeEnum,
  enrichmentJobModeEnum,
  enrichmentJobStatusEnum,
  enrichmentResultStatusEnum,
  enrichmentStageTypeEnum,
  templateTypeEnum,
  leadEnrichmentStatusEnum,
  leadEnrichmentSourceEnum,
  leadEnrichmentProviderEnum,
  type CrmEnrichmentJob,
  type NewCrmEnrichmentJob,
  type CrmEnrichmentResult,
  type NewCrmEnrichmentResult,
  type CrmToolCall,
  type NewCrmToolCall,
  type CrmEnrichmentAbTest,
  type NewCrmEnrichmentAbTest,
  type CrmEnrichmentPipeline,
  type NewCrmEnrichmentPipeline,
  type CrmPipelineStage,
  type NewCrmPipelineStage,
  type CrmTemplate,
  type NewCrmTemplate,
  type TemplateType,
  type CrmScoringModel, // Legacy alias
  type NewCrmScoringModel, // Legacy alias
  type LeadEnrichment,
  type NewLeadEnrichment,
  type LeadEnrichmentConfig,
  type NewLeadEnrichmentConfig,
  type EnrichmentJobType,
  type EnrichmentJobMode,
  type EnrichmentJobStatus,
  type EnrichmentResultStatus,
  type EnrichmentStageType,
  type LeadEnrichmentStatus,
  type LeadEnrichmentSource,
  type LeadEnrichmentProvider,
} from './enrichment';

// Export Enrichment History tables (US-ENRICH-HIST-001)
export {
  crmEnrichmentHistory,
  crmEnrichmentHistoryRelations,
  crmEnrichmentContent,
  crmEnrichmentContentRelations,
  type CrmEnrichmentHistory,
  type NewCrmEnrichmentHistory,
  type CrmEnrichmentContent,
  type NewCrmEnrichmentContent,
} from './enrichment-history';

// Export SDLC files tables
export {
  sdlcFiles,
  sdlcFilesRelations,
  sdlcFileOperationEnum,
  sdlcFileCategoryEnum,
  type SdlcFile,
  type NewSdlcFile,
  type SdlcFileOperation,
  type SdlcFileCategory,
} from './sdlc-files';

// Export CLI sessions tables
export {
  cliSessions,
  cliSessionsRelations,
  type CliSession,
  type NewCliSession,
} from './cli-sessions';

// Export Lead Management tables
export {
  bulkOperations,
  bulkOperationsRelations,
  bulkOperationItems,
  bulkOperationItemsRelations,
  leadSegments,
  leadSegmentsRelations,
  leadSegmentMemberships,
  leadSegmentMembershipsRelations,
  segmentMetricsHistory,
  segmentMetricsHistoryRelations,
  leadScoringModels,
  leadScoringModelsRelations,
  leadScores,
  leadScoresRelations,
  leadScoreHistory,
  leadScoreHistoryRelations,
  leadDataQuality,
  leadDataQualityRelations,
  leadNotes,
  leadNotesRelations,
  noteMentions,
  noteMentionsRelations,
  leadImports,
  leadImportsRelations,
  predictionModels,
  predictionModelsRelations,
  leadPredictions,
  leadPredictionsRelations,
  predictionHistory,
  predictionHistoryRelations,
  predictionTrainingData,
  predictionTrainingDataRelations,
  bulkOperationTypeEnum,
  bulkOperationStatusEnum,
  bulkOperationItemStatusEnum,
  scoringModelTypeEnum,
  importStatusEnum,
  duplicateStrategyEnum,
  validationModeEnum,
  predictionModelTypeEnum,
  predictionAlgorithmEnum,
  type BulkOperation,
  type NewBulkOperation,
  type BulkOperationItem,
  type NewBulkOperationItem,
  type LeadSegment,
  type NewLeadSegment,
  type LeadSegmentMembership,
  type NewLeadSegmentMembership,
  type SegmentMetricsHistory,
  type NewSegmentMetricsHistory,
  type LeadScoringModel,
  type NewLeadScoringModel,
  type LeadScore,
  type NewLeadScore,
  type LeadScoreHistory,
  type NewLeadScoreHistory,
  type LeadDataQuality,
  type NewLeadDataQuality,
  type LeadNote,
  type NewLeadNote,
  type NoteMention,
  type NewNoteMention,
  type LeadImport,
  type NewLeadImport,
  type PredictionModel,
  type NewPredictionModel,
  type LeadPrediction,
  type NewLeadPrediction,
  type PredictionHistory,
  type NewPredictionHistory,
  type PredictionTrainingData,
  type NewPredictionTrainingData,
  type BulkOperationType,
  type BulkOperationStatus,
  type BulkOperationItemStatus,
  type ScoringModelType,
  type ImportStatus,
  type DuplicateStrategy,
  type ValidationMode,
  type PredictionModelType,
  type PredictionAlgorithm,
} from './lead-management';

// Export Intent Signals tables (US-LEAD-AI-012)
export {
  intentSignalTypes,
  intentSignalTypesRelations,
  intentSignals,
  intentSignalsRelations,
  leadIntentScores,
  leadIntentScoresRelations,
  intentScoreHistory,
  intentScoreHistoryRelations,
  intentLevelEnum,
  intentActionEnum,
  signalCategoryEnum,
  type IntentSignalType,
  type NewIntentSignalType,
  type IntentSignal,
  type NewIntentSignal,
  type LeadIntentScore,
  type NewLeadIntentScore,
  type IntentScoreHistory,
  type NewIntentScoreHistory,
  type IntentLevel,
  type IntentAction,
  type SignalCategory,
} from './intent-signals';

// Export Routing tables (US-LEAD-AI-011)
export {
  agentProfiles,
  agentProfilesRelations,
  leadRoutingHistory,
  leadRoutingHistoryRelations,
  routingRules,
  routingRulesRelations,
  availabilityStatusEnum,
  routingStrategyEnum,
  type AgentProfile,
  type NewAgentProfile,
  type LeadRoutingHistory,
  type NewLeadRoutingHistory,
  type RoutingRule,
  type NewRoutingRule,
  type AvailabilityStatus,
  type RoutingStrategy,
} from './routing';
import {
  intentSignalTypes,
  intentSignalTypesRelations,
  intentSignals,
  intentSignalsRelations,
  leadIntentScores,
  leadIntentScoresRelations,
  intentScoreHistory,
  intentScoreHistoryRelations,
} from './intent-signals';

// Export Health Scoring tables
export {
  leadHealthScores,
  leadHealthScoresRelations,
  healthScoreHistory,
  healthScoreHistoryRelations,
  healthStatusEnum,
  healthTrendEnum,
  type LeadHealthScore,
  type NewLeadHealthScore,
  type HealthScoreHistory,
  type NewHealthScoreHistory,
  type HealthStatus,
  type HealthTrend,
} from './health-scoring';

// Export Batches tables
export {
  crmBatches,
  crmBatchesRelations,
  batchTypeEnum,
  batchStatusEnum,
  type CrmBatch,
  type NewCrmBatch,
  type BatchType,
  type BatchStatus,
} from './batches';

// Export AI Voice Calls tables
export {
  crmAiCalls,
  crmAiCallsRelations,
  crmAiCallEvents,
  crmAiCallEventsRelations,
  crmAiAgents,
  crmAiAgentsRelations,
  crmAiCallScripts,
  crmAiCallScriptsRelations,
  aiCallOutcomeEnum,
  aiCallSentimentEnum,
  aiCallEventTypeEnum,
  aiProviderEnum,
  aiCallDirectionEnum,
  type CrmAiCall,
  type NewCrmAiCall,
  type CrmAiCallEvent,
  type NewCrmAiCallEvent,
  type CrmAiAgent,
  type NewCrmAiAgent,
  type CrmAiCallScript,
  type NewCrmAiCallScript,
  type AiCallOutcome,
  type AiCallSentiment,
  type AiCallEventType,
  type AiProvider,
  type AiCallDirection,
  type AiCallEntityType,
} from './ai-voice-calls';

// Export AI Call Feedback tables (Phase M)
export {
  crmAiCallFeedback,
  crmAiCallFeedbackRelations,
  FEEDBACK_TAGS,
  type CrmAiCallFeedback,
  type NewCrmAiCallFeedback,
  type FeedbackTag,
  type FeedbackSummary,
} from './ai-call-feedback';

// Export AI Voice Campaigns tables (Phase N)
export {
  crmAiVoiceRateLimits,
  crmAiVoiceRateLimitsRelations,
  crmAiVoiceQueue,
  crmAiVoiceQueueRelations,
  AI_VOICE_DEFAULTS,
  type CrmAiVoiceRateLimit,
  type NewCrmAiVoiceRateLimit,
  type CrmAiVoiceQueue,
  type NewCrmAiVoiceQueue,
  type AiVoiceQueueStatus,
  type AiCallConfig,
} from './ai-voice-campaigns';

// Export Session Metrics types (US-001)
export {
  type SessionMetric,
  type SessionMetricsAggregate,
  type ToolUsageStats,
  type DurationAnalytics,
  type SessionMetricsSSEEvent,
  type SessionMetricsQueryParams,
} from './session-metrics';

// Export Job Logs tables (US-008)
export {
  jobLogs,
  jobLogLevelEnum,
  type JobLog,
  type NewJobLog,
  type JobLogLevel,
  type ToolCallMetadata,
  type EntityProcessingMetadata,
  type ProgressMetadata,
  type JobLogMetadata,
} from './job-logs';

// Export Work Items tables (US-014)
export {
  workItems,
  workItemsRelations,
  entityTypeEnum,
  workItemTypeEnum,
  workItemStatusEnum,
  completedByEnum,
  sourceTypeEnum,
  type WorkItem,
  type NewWorkItem,
  type EntityType,
  type WorkItemType,
  type WorkItemStatus,
  type CompletedBy,
  type SourceType,
} from './work-items';

// Export Tickets tables (Support & Product Feedback)
export {
  crmTickets,
  crmTicketsRelations,
  crmTicketComments,
  crmTicketCommentsRelations,
  ticketCategoryEnum,
  ticketPriorityEnum,
  ticketStatusEnum,
  ticketEntityTypeEnum,
  ticketSourceEnum,
  type CrmTicket,
  type NewCrmTicket,
  type CrmTicketComment,
  type NewCrmTicketComment,
  type TicketCategory,
  type TicketPriority,
  type TicketStatus,
  type TicketEntityType,
  type TicketSource,
} from './tickets';

// Export Calendar & Meeting Booking tables (Phase S)
export {
  crmCalendarConnections,
  crmCalendarConnectionsRelations,
  crmMeetings,
  crmMeetingsRelations,
  crmBookingLinks,
  crmBookingLinksRelations,
  type CrmCalendarConnection,
  type NewCrmCalendarConnection,
  type CrmMeeting,
  type NewCrmMeeting,
  type CrmBookingLink,
  type NewCrmBookingLink,
  type CalendarProvider,
  type CalendarSyncStatus,
  type MeetingStatus,
  type MeetingType,
  type AvailableHours,
} from './calendar';

// Export Integration Framework tables (Phase T)
export {
  crmWebhookSubscriptions,
  crmWebhookSubscriptionsRelations,
  crmWebhookDeliveries,
  crmWebhookDeliveriesRelations,
  crmApiKeys,
  crmApiKeysRelations,
  type CrmWebhookSubscription,
  type NewCrmWebhookSubscription,
  type CrmWebhookDelivery,
  type NewCrmWebhookDelivery,
  type CrmApiKey,
  type NewCrmApiKey,
  type RetryPolicy,
  type WebhookDeliveryStatus,
  type ApiKeyPermission,
} from './integrations';

// Export Advanced Automation tables (Phase U)
export {
  crmWorkflowApprovals,
  crmWorkflowApprovalsRelations,
  crmLeadRoutingRules,
  crmLeadRoutingRulesRelations,
  type CrmWorkflowApproval,
  type NewCrmWorkflowApproval,
  type CrmLeadRoutingRule,
  type NewCrmLeadRoutingRule,
  type ApprovalStatus,
  type RoutingEntityType,
} from './automation';

// Export CRM Data Sync tables (Phase V)
export {
  crmSyncConnections,
  crmSyncConnectionsRelations,
  crmFieldMappings,
  crmFieldMappingsRelations,
  crmSyncLogs,
  crmSyncLogsRelations,
  type CrmSyncConnection,
  type NewCrmSyncConnection,
  type CrmFieldMapping,
  type NewCrmFieldMapping,
  type CrmSyncLog,
  type NewCrmSyncLog,
  type SyncProvider,
  type SyncDirection,
  type SyncStatus,
  type SyncStats,
  type SyncEntityType,
  type FieldMappingDirection,
  type TransformType,
  type SyncType,
  type SyncLogStatus,
  type SyncErrorDetail,
} from './crm-sync';

// Export API usage monitoring tables
export {
  apiUsageSnapshots,
  apiUsageSnapshotsRelations,
  apiUsageAlerts,
  apiUsageAlertsRelations,
  apiProviderEnum,
  apiTrackingMethodEnum,
  apiAlertLevelEnum,
  type ApiUsageSnapshot,
  type NewApiUsageSnapshot,
  type ApiUsageAlert,
  type NewApiUsageAlert,
  type ApiProvider,
  type ApiTrackingMethod,
  type ApiAlertLevel,
} from './api-usage';

// Export schema for Drizzle
import { users } from './users';
import { sessions } from './sessions';
import { accounts } from './accounts';
import { deviceCodes } from './device-codes';
import { workspaces, workspacesRelations } from './workspaces';
import { workspaceMembers, workspaceMembersRelations } from './workspace-members';
import { workspaceInvitations, workspaceInvitationsRelations } from './workspace-invitations';
import { workspaceAuditLog, workspaceAuditLogRelations } from './workspace-audit-log';
import { projects } from './projects';
import { claudeSessions } from './claude-sessions';
import { hookEvents } from './hook-events';
import { eventSummaries } from './event-summaries';
import { chatMessages } from './chat-messages';
import { conversations, conversationsRelations, messages, messagesRelations } from './conversations';
import { llmConfigs, llmConfigsRelations } from './llm-configs';
import { llmCredentials } from './llm-credentials';
import { llmModelCatalog } from './llm-model-catalog';
import { voices } from './voices';
import {
  globalVoiceSettings,
  globalVoiceSettingsRelations,
  projectVoiceSettings,
  projectVoiceSettingsRelations,
} from './voice-settings';
import { models } from './models';
import { pronunciationDictionaries } from './pronunciation-dictionaries';
import { audioCache } from './audio-cache';
import { todos, todosRelations } from './todos';
import {
  crmAccounts,
  crmAccountsRelations,
  crmContacts,
  crmContactsRelations,
  crmLeads,
  crmLeadsRelations,
  crmLeadScoreHistory,
  crmLeadScoreHistoryRelations,
  crmOpportunities,
  crmOpportunitiesRelations,
  crmActivities,
  crmActivitiesRelations,
  crmTimelineEvents,
  crmTimelineEventsRelations,
  crmLeadImports,
  crmCalls,
  crmCallsRelations,
  crmEmailTemplates,
  crmEmailTemplatesRelations,
  crmSmsTemplates,
  crmSmsTemplatesRelations,
} from './crm';
import {
  crmCampaigns,
  crmCampaignsRelations,
  crmCampaignRecipients,
  crmCampaignRecipientsRelations,
  crmCampaignMessages,
  crmCampaignMessagesRelations,
  crmAbTestResults,
  crmAbTestResultsRelations,
  crmDripEnrollments,
  crmDripEnrollmentsRelations,
  crmCampaignSnapshots,
  crmCampaignSnapshotsRelations,
  crmTestSmsSessions,
  crmTestSmsSessionsRelations,
  crmMockMessages,
  crmMockMessagesRelations,
} from './campaigns';
import {
  campaignSchedules,
  campaignSchedulesRelations,
  campaignRecurrences,
  campaignRecurrencesRelations,
  campaignTriggers,
  campaignTriggersRelations,
  campaignTriggerExecutions,
  campaignTriggerExecutionsRelations,
  campaignTemplates,
  campaignTemplatesRelations,
  campaignWorkflows,
  campaignWorkflowsRelations,
  campaignWorkflowEnrollments,
  campaignWorkflowEnrollmentsRelations,
  campaignWorkflowExecutions,
  campaignWorkflowExecutionsRelations,
} from './campaign-automation';
import {
  crmResearchSessions,
  crmResearchSessionsRelations,
  crmResearchQueries,
  crmResearchQueriesRelations,
  crmResearchFindings,
  crmResearchFindingsRelations,
} from './research';
import {
  crmContactLists,
  crmContactListsRelations,
  crmContactListMemberships,
  crmContactListMembershipsRelations,
} from './contact-lists';
import {
  crmEnrichmentJobs,
  crmEnrichmentJobsRelations,
  crmEnrichmentResults,
  crmEnrichmentResultsRelations,
  crmToolCalls,
  crmToolCallsRelations,
  crmEnrichmentAbTests,
  crmEnrichmentPipelines,
  crmEnrichmentPipelinesRelations,
  crmPipelineStages,
  crmPipelineStagesRelations,
  crmTemplates,
  crmTemplatesRelations,
  crmScoringModels, // Legacy alias for crmTemplates
  crmScoringModelsRelations, // Legacy alias
  leadEnrichments,
  leadEnrichmentsRelations,
  leadEnrichmentConfigs,
  leadEnrichmentConfigsRelations,
} from './enrichment';
import {
  crmEnrichmentHistory,
  crmEnrichmentHistoryRelations,
  crmEnrichmentContent,
  crmEnrichmentContentRelations,
} from './enrichment-history';
import { sdlcFiles, sdlcFilesRelations } from './sdlc-files';
import { cliSessions, cliSessionsRelations } from './cli-sessions';
import {
  bulkOperations,
  bulkOperationsRelations,
  bulkOperationItems,
  bulkOperationItemsRelations,
  leadSegments,
  leadSegmentsRelations,
  leadSegmentMemberships,
  leadSegmentMembershipsRelations,
  segmentMetricsHistory,
  segmentMetricsHistoryRelations,
  leadScoringModels,
  leadScoringModelsRelations,
  leadScores,
  leadScoresRelations,
  leadScoreHistory,
  leadScoreHistoryRelations,
  leadDataQuality,
  leadDataQualityRelations,
  leadNotes,
  leadNotesRelations,
  noteMentions,
  noteMentionsRelations,
  leadImports,
  leadImportsRelations,
  predictionModels,
  predictionModelsRelations,
  leadPredictions,
  leadPredictionsRelations,
  predictionHistory,
  predictionHistoryRelations,
  predictionTrainingData,
  predictionTrainingDataRelations,
} from './lead-management';
import {
  intentSignalTypes,
  intentSignalTypesRelations,
  intentSignals,
  intentSignalsRelations,
  leadIntentScores,
  leadIntentScoresRelations,
  intentScoreHistory,
  intentScoreHistoryRelations,
} from './intent-signals';
import {
  leadHealthScores,
  leadHealthScoresRelations,
  healthScoreHistory,
  healthScoreHistoryRelations,
} from './health-scoring';
import {
  agentProfiles,
  agentProfilesRelations,
  leadRoutingHistory,
  leadRoutingHistoryRelations,
  routingRules,
  routingRulesRelations,
} from './routing';
import {
  intentSignalTypes,
  intentSignalTypesRelations,
  intentSignals,
  intentSignalsRelations,
  leadIntentScores,
  leadIntentScoresRelations,
  intentScoreHistory,
  intentScoreHistoryRelations,
} from './intent-signals';
import {
  aiConversations,
  aiConversationsRelations,
  aiMessages,
  aiMessagesRelations,
  aiConfig,
  aiConfigRelations,
  aiToolInvocations,
  aiToolInvocationsRelations,
  aiRateLimits,
  aiRateLimitsRelations,
  aiClaudeCodeSessions,
  aiClaudeCodeSessionsRelations,
} from './ai-assistant';
import {
  workspaceMemory,
  workspaceMemoryRelations,
  conversationSummaries,
  conversationSummariesRelations,
  workspaceSuggestions,
  workspaceSuggestionsRelations,
  tags,
} from './ai-intelligence.schema';
import {
  crmBatches,
  crmBatchesRelations,
} from './batches';
import {
  crmAiCalls,
  crmAiCallsRelations,
  crmAiCallEvents,
  crmAiCallEventsRelations,
  crmAiAgents,
  crmAiAgentsRelations,
  crmAiCallScripts,
  crmAiCallScriptsRelations,
} from './ai-voice-calls';
import {
  crmAiCallFeedback,
  crmAiCallFeedbackRelations,
} from './ai-call-feedback';
import {
  crmAiVoiceRateLimits,
  crmAiVoiceRateLimitsRelations,
  crmAiVoiceQueue,
  crmAiVoiceQueueRelations,
} from './ai-voice-campaigns';
import { jobLogs } from './job-logs';
import { workItems, workItemsRelations } from './work-items';
import {
  crmTickets,
  crmTicketsRelations,
  crmTicketComments,
  crmTicketCommentsRelations,
} from './tickets';
import {
  crmEmailSuppressions,
  crmEmailSuppressionsRelations,
  crmEmailRateLimits,
  crmEmailRateLimitsRelations,
} from './email-suppressions';
import {
  crmCalendarConnections,
  crmCalendarConnectionsRelations,
  crmMeetings,
  crmMeetingsRelations,
  crmBookingLinks,
  crmBookingLinksRelations,
} from './calendar';
import {
  crmWebhookSubscriptions,
  crmWebhookSubscriptionsRelations,
  crmWebhookDeliveries,
  crmWebhookDeliveriesRelations,
  crmApiKeys,
  crmApiKeysRelations,
} from './integrations';
import {
  crmWorkflowApprovals,
  crmWorkflowApprovalsRelations,
  crmLeadRoutingRules,
  crmLeadRoutingRulesRelations,
} from './automation';
import {
  crmSyncConnections,
  crmSyncConnectionsRelations,
  crmFieldMappings,
  crmFieldMappingsRelations,
  crmSyncLogs,
  crmSyncLogsRelations,
} from './crm-sync';
import {
  apiUsageSnapshots,
  apiUsageSnapshotsRelations,
  apiUsageAlerts,
  apiUsageAlertsRelations,
} from './api-usage';

export const schema = {
  users,
  sessions,
  accounts,
  deviceCodes,
  workspaces,
  workspacesRelations,
  workspaceMembers,
  workspaceMembersRelations,
  workspaceInvitations,
  workspaceInvitationsRelations,
  workspaceAuditLog,
  workspaceAuditLogRelations,
  projects,
  claudeSessions,
  hookEvents,
  eventSummaries,
  chatMessages,
  conversations,
  conversationsRelations,
  messages,
  messagesRelations,
  llmConfigs,
  llmConfigsRelations,
  llmCredentials,
  llmModelCatalog,
  voices,
  globalVoiceSettings,
  globalVoiceSettingsRelations,
  projectVoiceSettings,
  projectVoiceSettingsRelations,
  models,
  pronunciationDictionaries,
  audioCache,
  todos,
  todosRelations,
  aiConversations,
  aiConversationsRelations,
  aiMessages,
  aiMessagesRelations,
  aiConfig,
  aiConfigRelations,
  aiToolInvocations,
  aiToolInvocationsRelations,
  aiRateLimits,
  aiRateLimitsRelations,
  aiClaudeCodeSessions,
  aiClaudeCodeSessionsRelations,
  workspaceMemory,
  workspaceMemoryRelations,
  conversationSummaries,
  conversationSummariesRelations,
  workspaceSuggestions,
  workspaceSuggestionsRelations,
  tags,
  crmAccounts,
  crmAccountsRelations,
  crmContacts,
  crmContactsRelations,
  crmLeads,
  crmLeadsRelations,
  crmLeadScoreHistory,
  crmLeadScoreHistoryRelations,
  crmOpportunities,
  crmOpportunitiesRelations,
  crmActivities,
  crmActivitiesRelations,
  crmTimelineEvents,
  crmTimelineEventsRelations,
  crmLeadImports,
  crmCalls,
  crmCallsRelations,
  crmEmailTemplates,
  crmEmailTemplatesRelations,
  crmSmsTemplates,
  crmSmsTemplatesRelations,
  crmCampaigns,
  crmCampaignsRelations,
  crmCampaignRecipients,
  crmCampaignRecipientsRelations,
  crmCampaignMessages,
  crmCampaignMessagesRelations,
  crmAbTestResults,
  crmAbTestResultsRelations,
  crmDripEnrollments,
  crmDripEnrollmentsRelations,
  crmCampaignSnapshots,
  crmCampaignSnapshotsRelations,
  crmTestSmsSessions,
  crmTestSmsSessionsRelations,
  crmMockMessages,
  crmMockMessagesRelations,
  campaignSchedules,
  campaignSchedulesRelations,
  campaignRecurrences,
  campaignRecurrencesRelations,
  campaignTriggers,
  campaignTriggersRelations,
  campaignTriggerExecutions,
  campaignTriggerExecutionsRelations,
  campaignTemplates,
  campaignTemplatesRelations,
  campaignWorkflows,
  campaignWorkflowsRelations,
  campaignWorkflowEnrollments,
  campaignWorkflowEnrollmentsRelations,
  campaignWorkflowExecutions,
  campaignWorkflowExecutionsRelations,
  crmResearchSessions,
  crmResearchSessionsRelations,
  crmResearchQueries,
  crmResearchQueriesRelations,
  crmResearchFindings,
  crmResearchFindingsRelations,
  crmContactLists,
  crmContactListsRelations,
  crmContactListMemberships,
  crmContactListMembershipsRelations,
  crmEnrichmentJobs,
  crmEnrichmentJobsRelations,
  crmEnrichmentResults,
  crmEnrichmentResultsRelations,
  crmToolCalls,
  crmToolCallsRelations,
  crmEnrichmentAbTests,
  crmEnrichmentPipelines,
  crmEnrichmentPipelinesRelations,
  crmPipelineStages,
  crmPipelineStagesRelations,
  crmTemplates,
  crmTemplatesRelations,
  crmScoringModels, // Legacy alias for crmTemplates
  crmScoringModelsRelations, // Legacy alias
  leadEnrichments,
  leadEnrichmentsRelations,
  leadEnrichmentConfigs,
  leadEnrichmentConfigsRelations,
  crmEnrichmentHistory,
  crmEnrichmentHistoryRelations,
  crmEnrichmentContent,
  crmEnrichmentContentRelations,
  sdlcFiles,
  sdlcFilesRelations,
  cliSessions,
  cliSessionsRelations,
  bulkOperations,
  bulkOperationsRelations,
  bulkOperationItems,
  bulkOperationItemsRelations,
  leadSegments,
  leadSegmentsRelations,
  leadSegmentMemberships,
  leadSegmentMembershipsRelations,
  segmentMetricsHistory,
  segmentMetricsHistoryRelations,
  leadScoringModels,
  leadScoringModelsRelations,
  leadScores,
  leadScoresRelations,
  leadScoreHistory,
  leadScoreHistoryRelations,
  leadDataQuality,
  leadDataQualityRelations,
  leadNotes,
  leadNotesRelations,
  noteMentions,
  noteMentionsRelations,
  leadImports,
  leadImportsRelations,
  predictionModels,
  predictionModelsRelations,
  leadPredictions,
  leadPredictionsRelations,
  predictionHistory,
  predictionHistoryRelations,
  predictionTrainingData,
  predictionTrainingDataRelations,
  intentSignalTypes,
  intentSignalTypesRelations,
  intentSignals,
  intentSignalsRelations,
  leadIntentScores,
  leadIntentScoresRelations,
  intentScoreHistory,
  intentScoreHistoryRelations,
  leadHealthScores,
  leadHealthScoresRelations,
  healthScoreHistory,
  healthScoreHistoryRelations,
  agentProfiles,
  agentProfilesRelations,
  leadRoutingHistory,
  leadRoutingHistoryRelations,
  routingRules,
  routingRulesRelations,
  crmBatches,
  crmBatchesRelations,
  crmAiCalls,
  crmAiCallsRelations,
  crmAiCallEvents,
  crmAiCallEventsRelations,
  crmAiAgents,
  crmAiAgentsRelations,
  crmAiCallScripts,
  crmAiCallScriptsRelations,
  crmAiCallFeedback,
  crmAiCallFeedbackRelations,
  crmAiVoiceRateLimits,
  crmAiVoiceRateLimitsRelations,
  crmAiVoiceQueue,
  crmAiVoiceQueueRelations,
  jobLogs,
  workItems,
  workItemsRelations,
  crmTickets,
  crmTicketsRelations,
  crmTicketComments,
  crmTicketCommentsRelations,
  crmEmailSuppressions,
  crmEmailSuppressionsRelations,
  crmEmailRateLimits,
  crmEmailRateLimitsRelations,
  crmCalendarConnections,
  crmCalendarConnectionsRelations,
  crmMeetings,
  crmMeetingsRelations,
  crmBookingLinks,
  crmBookingLinksRelations,
  crmWebhookSubscriptions,
  crmWebhookSubscriptionsRelations,
  crmWebhookDeliveries,
  crmWebhookDeliveriesRelations,
  crmApiKeys,
  crmApiKeysRelations,
  crmWorkflowApprovals,
  crmWorkflowApprovalsRelations,
  crmLeadRoutingRules,
  crmLeadRoutingRulesRelations,
  crmSyncConnections,
  crmSyncConnectionsRelations,
  crmFieldMappings,
  crmFieldMappingsRelations,
  crmSyncLogs,
  crmSyncLogsRelations,
  apiUsageSnapshots,
  apiUsageSnapshotsRelations,
  apiUsageAlerts,
  apiUsageAlertsRelations,
};
